### ISSUE TITLE
AttributeError: 'HttpUrl' object has no attribute 'proxy_type'

### ISSUE THREAD

**Issue by gr1ev0us** [wummel/linkchecker#555]
The problem appears when i chek local web-site:
linkchecker --ignore-url=^mailto: www.sintez.dev

I've tried to change 'url_data.proxy_type' to 'url_data.proxytype', but it creates a new error in /usr/local/lib/python2.7/dist-packages/requests/sessions.py:
AttributeError: 'set' object has no attribute 'setdefault' 

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 104, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-http://www.sintezr.dev, started 139842591651584)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-http://www.sintezr.dev, started 139842591651584)>>
      url_data = <local> <http link, base_url=u'http://www.sintezr.dev', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=http://www.sintezr.dev>
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 120, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x7f2fabdbbc08>
      url_data = <local> <http link, base_url=u'http://www.sintezr.dev', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=http://www.sintezr.dev>
      self = <local> <Checker(CheckThread-http://www.sintezr.dev, started 139842591651584)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x7f2fa8f18410>
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 52, in check_url
    line: url_data.check()
    locals:
      url_data = <local> <http link, base_url=u'http://www.sintezr.dev', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=http://www.sintezr.dev>
      url_data.check = <local> <bound method HttpUrl.check of <http link, base_url=u'http://www.sintezr.dev', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=http://www.sintezr.dev>>
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 424, in check
    line: self.local_check()
    locals:
      self = <local> <http link, base_url=u'http://www.sintezr.dev', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=http://www.sintezr.dev>
      self.local_check = <local> <bound method HttpUrl.local_check of <http link, base_url=u'http://www.sintezr.dev', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=http://www.sintezr.dev>>
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 442, in local_check
    line: self.check_connection()
    locals:
      self = <local> <http link, base_url=u'http://www.sintezr.dev', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=http://www.sintezr.dev>
      self.check_connection = <local> <bound method HttpUrl.check_connection of <http link, base_url=u'http://www.sintezr.dev', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=http://www.sintezr.dev>>
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 128, in check_connection
    line: if not self.allows_robots(self.url):
    locals:
      self = <local> <http link, base_url=u'http://www.sintezr.dev', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=http://www.sintezr.dev>
      self.allows_robots = <local> <bound method HttpUrl.allows_robots of <http link, base_url=u'http://www.sintezr.dev', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=http://www.sintezr.dev>>
      self.url = <local> u'http://www.sintezr.dev', len = 22
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 66, in allows_robots
    line: return self.aggregate.robots_txt.allows_url(self)
    locals:
      self = <local> <http link, base_url=u'http://www.sintezr.dev', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=http://www.sintezr.dev>
      self.aggregate = <local> <linkcheck.director.aggregator.Aggregate object at 0x7f2fa8f18390>
      self.aggregate.robots_txt = <local> <linkcheck.cache.robots_txt.RobotsTxt object at 0x7f2fa8f18310>
      self.aggregate.robots_txt.allows_url = <local> <bound method RobotsTxt.allows_url of <linkcheck.cache.robots_txt.RobotsTxt object at 0x7f2fa8f18310>>
  File "/usr/lib/python2.7/dist-packages/linkcheck/cache/robots_txt.py", line 49, in allows_url
    line: return self._allows_url(url_data, roboturl)
    locals:
      self = <local> <linkcheck.cache.robots_txt.RobotsTxt object at 0x7f2fa8f18310>
      self._allows_url = <local> <bound method RobotsTxt._allows_url of <linkcheck.cache.robots_txt.RobotsTxt object at 0x7f2fa8f18310>>
      url_data = <local> <http link, base_url=u'http://www.sintezr.dev', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=http://www.sintezr.dev>
      roboturl = <local> u'http://www.sintezr.dev/robots.txt', len = 33
  File "/usr/lib/python2.7/dist-packages/linkcheck/cache/robots_txt.py", line 62, in _allows_url
    line: kwargs["proxies"] = {url_data.proxy_type, url_data.proxy}
    locals:
      kwargs = <local> {'session': <requests.sessions.Session object at 0x7f2fa8f18690>, 'auth': None}
      url_data = <local> <http link, base_url=u'http://www.sintezr.dev', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=http://www.sintezr.dev>
      url_data.proxy_type = <local> !AttributeError: 'HttpUrl' object has no attribute 'proxy_type'
      url_data.proxy = <local> '192.168.1.254:3128', len = 18
AttributeError: 'HttpUrl' object has no attribute 'proxy_type'
System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2

Statistics:
Downloaded: 0B.
No statistics available since no URLs were checked.

That's it. 0 links in 0 URLs checked. 0 warnings found. 0 errors found.
Stopped checking at 2014-10-09 14:16:08+004 (0.06 seconds)
Requests: 2.4.1
Qt: 4.8.6 / PyQt: 4.10.4
Modules: Sqlite, Gconf
Local time: 2014-10-09 14:16:08+004
sys.argv: ['/usr/bin/linkchecker', 'www.sintezr.dev']
http_proxy = 'http://192.168.1.254:3128/'
no_proxy = 'localhost,127.0.0.0/8,::1,_.dev,192.168._,10.10.20.67'
LANGUAGE = 'ru:en'
LANG = 'ru_RU.UTF-8'
Default locale: ('ru', 'UTF-8')

**Comment by mgedmin** [comment]
See also commits https://github.com/wummel/linkchecker/commit/52337f82cbc89c93929c16a8dd3eb0df60150300 and https://github.com/wummel/linkchecker/commit/4e56eceb358ae9e9c25833adbc44b761d321b586.
