### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by davidvasandani** [wummel/linkchecker#565]
URL: https://m.warbyparker.com'
command: linkchecker https://m.warbyparker.com

This used to work but started giving us errors today.

```
Traceback (most recent call last):
  File "/opt/wp/virtualenv/hegemon/lib/python2.7/site-packages/linkcheck/director/checker.py", line 104, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-https://m.warbyparker.com/sunglasses/women/benchley/oak-barrel, started 140145535723264)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-https://m.warbyparker.com/sunglasses/women/benchley/oak-barrel, started 140145535723264)>>
      url_data = <local> <https link, base_url=u'/sunglasses/women/benchley/oak-barrel', parent_url=u'https://m.warbyparker.com/sunglasses/women/benchley/crystal', base_ref=None, recursion_level=4, url_connection=None, line=326, column=229, page=0, name=u'Oak Barrel', anchor=u'', cache_url=https://m.warbyparker.com/sungl...
  File "/opt/wp/virtualenv/hegemon/lib/python2.7/site-packages/linkcheck/director/checker.py", line 120, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x2365938>
      url_data = <local> <https link, base_url=u'/sunglasses/women/benchley/oak-barrel', parent_url=u'https://m.warbyparker.com/sunglasses/women/benchley/crystal', base_ref=None, recursion_level=4, url_connection=None, line=326, column=229, page=0, name=u'Oak Barrel', anchor=u'', cache_url=https://m.warbyparker.com/sungl...
      self = <local> <Checker(CheckThread-https://m.warbyparker.com/sunglasses/women/benchley/oak-barrel, started 140145535723264)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x289ce10>
  File "/opt/wp/virtualenv/hegemon/lib/python2.7/site-packages/linkcheck/director/checker.py", line 64, in check_url
    line: parser.parse_url(url_data)
    locals:
      parser = <global> <module 'linkcheck.parser' from '/opt/wp/virtualenv/hegemon/lib/python2.7/site-packages/linkcheck/parser/__init__.py'>
      parser.parse_url = <global> <function parse_url at 0x2362f50>
      url_data = <local> <https link, base_url=u'/sunglasses/women/benchley/oak-barrel', parent_url=u'https://m.warbyparker.com/sunglasses/women/benchley/crystal', base_ref=None, recursion_level=4, url_connection=None, line=326, column=229, page=0, name=u'Oak Barrel', anchor=u'', cache_url=https://m.warbyparker.com/sungl...
  File "/opt/wp/virtualenv/hegemon/lib/python2.7/site-packages/linkcheck/parser/__init__.py", line 39, in parse_url
    line: globals()[funcname](url_data)
    locals:
      globals = <builtin> <built-in function globals>
      funcname = <local> 'parse_html', len = 10
      url_data = <local> <https link, base_url=u'/sunglasses/women/benchley/oak-barrel', parent_url=u'https://m.warbyparker.com/sunglasses/women/benchley/crystal', base_ref=None, recursion_level=4, url_connection=None, line=326, column=229, page=0, name=u'Oak Barrel', anchor=u'', cache_url=https://m.warbyparker.com/sungl...
  File "/opt/wp/virtualenv/hegemon/lib/python2.7/site-packages/linkcheck/parser/__init__.py", line 48, in parse_html
    line: find_links(url_data, url_data.add_url, linkparse.LinkTags)
    locals:
      find_links = <global> <function find_links at 0x2365410>
      url_data = <local> <https link, base_url=u'/sunglasses/women/benchley/oak-barrel', parent_url=u'https://m.warbyparker.com/sunglasses/women/benchley/crystal', base_ref=None, recursion_level=4, url_connection=None, line=326, column=229, page=0, name=u'Oak Barrel', anchor=u'', cache_url=https://m.warbyparker.com/sungl...
      url_data.add_url = <local> <bound method HttpUrl.add_url of <https link, base_url=u'/sunglasses/women/benchley/oak-barrel', parent_url=u'https://m.warbyparker.com/sunglasses/women/benchley/crystal', base_ref=None, recursion_level=4, url_connection=None, line=326, column=229, page=0, name=u'Oak Barrel', anchor=u'', cache_ur...
      linkparse = <global> <module 'linkcheck.htmlutil.linkparse' from '/opt/wp/virtualenv/hegemon/lib/python2.7/site-packages/linkcheck/htmlutil/linkparse.py'>
      linkparse.LinkTags = <global> {'audio': [u'src'], 'layer': [u'background', u'src'], 'source': [u'src'], 'video': [u'src'], 'ilayer': [u'background'], 'tr': [u'background'], 'bgsound': [u'src'], 'body': [u'background'], 'th': [u'background'], 'html': [u'manifest'], 'frame': [u'src', u'longdesc'], 'td': [u'background'], 'iframe..., len = 35
  File "/opt/wp/virtualenv/hegemon/lib/python2.7/site-packages/linkcheck/parser/__init__.py", line 126, in find_links
    line: parser.feed(url_data.get_content())
    locals:
      parser = <local> <linkcheck.HtmlParser.htmlsax.parser object at 0x7f763001d050>
      parser.feed = <local> <built-in method feed of linkcheck.HtmlParser.htmlsax.parser object at 0x7f763001d050>
      url_data = <local> <https link, base_url=u'/sunglasses/women/benchley/oak-barrel', parent_url=u'https://m.warbyparker.com/sunglasses/women/benchley/crystal', base_ref=None, recursion_level=4, url_connection=None, line=326, column=229, page=0, name=u'Oak Barrel', anchor=u'', cache_url=https://m.warbyparker.com/sungl...
      url_data.get_content = <local> <bound method HttpUrl.get_content of <https link, base_url=u'/sunglasses/women/benchley/oak-barrel', parent_url=u'https://m.warbyparker.com/sunglasses/women/benchley/crystal', base_ref=None, recursion_level=4, url_connection=None, line=326, column=229, page=0, name=u'Oak Barrel', anchor=u'', cach...
  File "/opt/wp/virtualenv/hegemon/lib/python2.7/site-packages/linkcheck/htmlutil/linkparse.py", line 231, in start_element
    line: self.parse_tag(tag, attr, value, name, base)
    locals:
      self = <local> <linkcheck.htmlutil.linkparse.LinkFinder object at 0x7f76181eb2d0>
      self.parse_tag = <local> <bound method LinkFinder.parse_tag of <linkcheck.htmlutil.linkparse.LinkFinder object at 0x7f76181eb2d0>>
      tag = <local> u'img'
      attr = <local> u'srcset', len = 6
      value = <local> u',  2x'
      name = <local> u'Oak Barrel', len = 10
      base = <local> u''
  File "/opt/wp/virtualenv/hegemon/lib/python2.7/site-packages/linkcheck/htmlutil/linkparse.py", line 274, in parse_tag
    line: url = img_candidate.split()[0]
    locals:
      url = <not found>
      img_candidate = <local> u''
      img_candidate.split = <local> <built-in method split of unicode object at 0x7f764c286180>
IndexError: list index out of range
System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.5 (default, Dec  2 2013, 03:22:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
PYTHONPATH = '/opt/wp/app/hegemon/python'
PYTHONDONTWRITEBYTECODE = '1'
PYTHONUNBUFFERED = '1'
Requests: 2.3.0
Modules: Sqlite
Local time: 2014-12-09 22:50:41+001
sys.argv: ['/opt/wp/virtualenv/hegemon/bin/linkchecker', 'https://m.warbyparker.com']
LANG = 'en_US.UTF-8'
Default locale: ('en', 'UTF-8')
```

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues if your issue still persists
