### ISSUE TITLE
 ********** Oops, I did it again. *************

### ISSUE THREAD

**Issue by aizen316** [wummel/linkchecker#572]
Traceback (most recent call last):
  File "linkcheck\director\checker.pyo", line 104, in check_url
    -- code not available --
  File "linkcheck\director\checker.pyo", line 120, in check_url_data
    -- code not available --
  File "linkcheck\director\checker.pyo", line 52, in check_url
    -- code not available --
  File "linkcheck\checker\urlbase.pyo", line 424, in check
    -- couldn't find file, trying this instead: E:\linkchecker\LinkChecker\library.zip\linkcheck\checker\urlbase.py
    -- code not available --
  File "linkcheck\checker\urlbase.pyo", line 442, in local_check
    -- couldn't find file, trying this instead: E:\linkchecker\LinkChecker\library.zip\linkcheck\checker\urlbase.py
    -- code not available --
  File "linkcheck\checker\httpurl.pyo", line 128, in check_connection
    -- couldn't find file, trying this instead: E:\linkchecker\LinkChecker\library.zip\linkcheck\checker\httpurl.py
    -- code not available --
  File "linkcheck\checker\httpurl.pyo", line 66, in allows_robots
    -- couldn't find file, trying this instead: E:\linkchecker\LinkChecker\library.zip\linkcheck\checker\httpurl.py
    -- code not available --
  File "linkcheck\cache\robots_txt.pyo", line 49, in allows_url
    -- couldn't find file, trying this instead: E:\linkchecker\LinkChecker\library.zip\linkcheck\cache\robots_txt.py
    -- code not available --
  File "linkcheck\cache\robots_txt.pyo", line 62, in _allows_url
    -- couldn't find file, trying this instead: E:\linkchecker\LinkChecker\library.zip\linkcheck\cache\robots_txt.py
    -- code not available --
AttributeError: 'HttpUrl' object has no attribute 'proxy_type'
System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
Requests: 2.2.1
Qt: 4.8.6 / PyQt: 4.11
Modules: QScintilla, Sqlite
Local time: 2015-01-15 11:10:52+005
sys.argv: ['E:\\linkchecker\\LinkChecker\\linkchecker-gui.exe']
Default locale: ('en', 'cp1252')

 ******** LinkChecker internal error, over and out ********

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues if your issue still persists
