### ISSUE TITLE
Does anyone get this after make app?

### ISSUE THREAD

**Issue by emreozen** [wummel/linkchecker#576]
python2.7 setup.py py2app 
Traceback (most recent call last):
  File "setup.py", line 671, in <module>
    add_qt_plugin_files(data_files)
  File "setup.py", line 241, in add_qt_plugin_files
    plugin_dir = get_qt_plugin_dir_osx()
  File "setup.py", line 225, in get_qt_plugin_dir_osx
    qtbindir = os.path.dirname(os.path.realpath(find_executable("qmake")))
  File "/Users/XL/Documents/workspace/linkchecker/venv/lib/python2.7/posixpath.py", line 367, in realpath
    path, ok = _joinrealpath('', filename, {})
  File "/Users/XL/Documents/workspace/linkchecker/venv/lib/python2.7/posixpath.py", line 373, in _joinrealpath
    if isabs(rest):
  File "/Users/XL/Documents/workspace/linkchecker/venv/lib/python2.7/posixpath.py", line 61, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
make: *** [app] Error 1

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues if your issue still persists
