### ISSUE TITLE
Installation on Enterprise Linux failure

### ISSUE THREAD

**Issue by bgoldowsky** [wummel/linkchecker#587]
Tried install on Scientific Linux 6 -- which is essentially identical to Red Hat or CentOS.

Installation with this command finished without errors:
   sudo pip install LinkChecker

However, running linkchecker fails:

$ linkchecker --help
Traceback (most recent call last):
  File "/usr/bin/linkchecker", line 5, in <module>
    pkg_resources.run_script('LinkChecker==9.3', 'linkchecker')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/LinkChecker-9.3-py2.6-linux-i686.egg/EGG-INFO/scripts/linkchecker", line 32, in <module>
    logconf.init_log_config()
  File "/usr/lib/python2.6/site-packages/LinkChecker-9.3-py2.6-linux-i686.egg/linkcheck/logconf.py", line 66, in init_log_config
    logging.config.dictConfig(configdict)
AttributeError: 'module' object has no attribute 'dictConfig'

Any suggestions on how to proceed?

Boris

**Comment by bgoldowsky** [comment]
On closer investigation, I see that linkchecker has specified python 2.7 as a requirement and I have 2.6.  Probably this is the source of the problem.

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues if your issue still persists
