### ISSUE TITLE
Internal error checking link to youtube video

### ISSUE THREAD

**Issue by gabrimonfa** [wummel/linkchecker#610]
You have found an internal error in LinkChecker. 

<snip>

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 104, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-http://www.youtube.com/v/9qR38KZSe34?version=3&fs=0&autoplay=0&rel=1, started 139641544701696)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-http://www.youtube.com/v/9qR38KZSe34?version=3&fs=0&autoplay=0&rel=1, started 139641544701696)>>
      url_data = <local> <https link, base_url=u'http://www.youtube.com/v/9qR38KZSe34?version=3&fs=0&autoplay=0&rel=1', parent_url=u'http://maps1.ldpgis.it/massimolippi/?q=node/20', base_ref=None, recursion_level=3, url_connection=None, line=109, column=294, page=0, name=u'', anchor=u'', cache_url=http://www.youtube.com/...
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 120, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x7f00d9a51d70>
      url_data = <local> <https link, base_url=u'http://www.youtube.com/v/9qR38KZSe34?version=3&fs=0&autoplay=0&rel=1', parent_url=u'http://maps1.ldpgis.it/massimolippi/?q=node/20', base_ref=None, recursion_level=3, url_connection=None, line=109, column=294, page=0, name=u'', anchor=u'', cache_url=http://www.youtube.com/...
      self = <local> <Checker(CheckThread-http://www.youtube.com/v/9qR38KZSe34?version=3&fs=0&autoplay=0&rel=1, started 139641544701696)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x7f00d932dc10>
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 52, in check_url
    line: url_data.check()
    locals:
      url_data = <local> <https link, base_url=u'http://www.youtube.com/v/9qR38KZSe34?version=3&fs=0&autoplay=0&rel=1', parent_url=u'http://maps1.ldpgis.it/massimolippi/?q=node/20', base_ref=None, recursion_level=3, url_connection=None, line=109, column=294, page=0, name=u'', anchor=u'', cache_url=http://www.youtube.com/...
      url_data.check = <local> <bound method HttpUrl.check of <https link, base_url=u'http://www.youtube.com/v/9qR38KZSe34?version=3&fs=0&autoplay=0&rel=1', parent_url=u'http://maps1.ldpgis.it/massimolippi/?q=node/20', base_ref=None, recursion_level=3, url_connection=None, line=109, column=294, page=0, name=u'', anchor=u'', ca...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 424, in check
    line: self.local_check()
    locals:
      self = <local> <https link, base_url=u'http://www.youtube.com/v/9qR38KZSe34?version=3&fs=0&autoplay=0&rel=1', parent_url=u'http://maps1.ldpgis.it/massimolippi/?q=node/20', base_ref=None, recursion_level=3, url_connection=None, line=109, column=294, page=0, name=u'', anchor=u'', cache_url=http://www.youtube.com/...
      self.local_check = <local> <bound method HttpUrl.local_check of <https link, base_url=u'http://www.youtube.com/v/9qR38KZSe34?version=3&fs=0&autoplay=0&rel=1', parent_url=u'http://maps1.ldpgis.it/massimolippi/?q=node/20', base_ref=None, recursion_level=3, url_connection=None, line=109, column=294, page=0, name=u'', anchor=u...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 442, in local_check
    line: self.check_connection()
    locals:
      self = <local> <https link, base_url=u'http://www.youtube.com/v/9qR38KZSe34?version=3&fs=0&autoplay=0&rel=1', parent_url=u'http://maps1.ldpgis.it/massimolippi/?q=node/20', base_ref=None, recursion_level=3, url_connection=None, line=109, column=294, page=0, name=u'', anchor=u'', cache_url=http://www.youtube.com/...
      self.check_connection = <local> <bound method HttpUrl.check_connection of <https link, base_url=u'http://www.youtube.com/v/9qR38KZSe34?version=3&fs=0&autoplay=0&rel=1', parent_url=u'http://maps1.ldpgis.it/massimolippi/?q=node/20', base_ref=None, recursion_level=3, url_connection=None, line=109, column=294, page=0, name=u'', anc...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 137, in check_connection
    line: self.follow_redirections(request)
    locals:
      self = <local> <https link, base_url=u'http://www.youtube.com/v/9qR38KZSe34?version=3&fs=0&autoplay=0&rel=1', parent_url=u'http://maps1.ldpgis.it/massimolippi/?q=node/20', base_ref=None, recursion_level=3, url_connection=None, line=109, column=294, page=0, name=u'', anchor=u'', cache_url=http://www.youtube.com/...
      self.follow_redirections = <local> <bound method HttpUrl.follow_redirections of <https link, base_url=u'http://www.youtube.com/v/9qR38KZSe34?version=3&fs=0&autoplay=0&rel=1', parent_url=u'http://maps1.ldpgis.it/massimolippi/?q=node/20', base_ref=None, recursion_level=3, url_connection=None, line=109, column=294, page=0, name=u'', ...
      request = <local> <PreparedRequest [GET]>
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 263, in follow_redirections
    line: self._add_ssl_info()
    locals:
      self = <local> <https link, base_url=u'http://www.youtube.com/v/9qR38KZSe34?version=3&fs=0&autoplay=0&rel=1', parent_url=u'http://maps1.ldpgis.it/massimolippi/?q=node/20', base_ref=None, recursion_level=3, url_connection=None, line=109, column=294, page=0, name=u'', anchor=u'', cache_url=http://www.youtube.com/...
      self._add_ssl_info = <local> <bound method HttpUrl._add_ssl_info of <https link, base_url=u'http://www.youtube.com/v/9qR38KZSe34?version=3&fs=0&autoplay=0&rel=1', parent_url=u'http://maps1.ldpgis.it/massimolippi/?q=node/20', base_ref=None, recursion_level=3, url_connection=None, line=109, column=294, page=0, name=u'', anchor...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 199, in _add_ssl_info
    line: self.ssl_cert = httputil.x509_to_dict(cert)
    locals:
      self = <local> <https link, base_url=u'http://www.youtube.com/v/9qR38KZSe34?version=3&fs=0&autoplay=0&rel=1', parent_url=u'http://maps1.ldpgis.it/massimolippi/?q=node/20', base_ref=None, recursion_level=3, url_connection=None, line=109, column=294, page=0, name=u'', anchor=u'', cache_url=http://www.youtube.com/...
      self.ssl_cert = <local> None
      httputil = <global> <module 'linkcheck.httputil' from '/usr/lib/python2.7/dist-packages/linkcheck/httputil.pyc'>
      httputil.x509_to_dict = <global> <function x509_to_dict at 0x7f00d9d710c8>
      cert = <local> <X509 object at 0x7f00bcad28f0>
  File "/usr/lib/python2.7/dist-packages/linkcheck/httputil.py", line 35, in x509_to_dict
    line: from requests.packages.urllib3.contrib.pyopenssl import get_subj_alt_name
    locals:
      requests = <not found>
      requests.packages = <not found>
      requests.packages.urllib3 = <not found>
      requests.packages.urllib3.contrib = <not found>
      requests.packages.urllib3.contrib.pyopenssl = <not found>
      get_subj_alt_name = <not found>
ImportError: cannot import name get_subj_alt_name
System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2

**Comment by anarcat** [comment]
this is fixed in #656

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues if your issue still persists
