### ISSUE TITLE
Unable to load linkchecker-gui due to incorrect share path

### ISSUE THREAD

**Issue by acdha** [wummel/linkchecker#619]
On OS X 10.11, using pip 7.1.2 with Python 2.7.10 from Homebrew: 

* `pip install LinkChecker` works
* `linkchecker http://example.org` works
* `linkchecker-gui` fails:
```
cadams@Ganymede:~ $ linkchecker-gui --help
Traceback (most recent call last):
  File "/usr/local/bin/linkchecker-gui", line 78, in <module>
    main()
  File "/usr/local/bin/linkchecker-gui", line 68, in main
    window = LinkCheckerMain(**mainkwargs)
  File "/usr/local/lib/python2.7/site-packages/linkcheck/gui/__init__.py", line 105, in __init__
    self.assistant = HelpWindow(self, self.get_qhcpath())
  File "/usr/local/lib/python2.7/site-packages/linkcheck/gui/__init__.py", line 185, in get_qhcpath
    return configuration.get_share_file('lccollection.qhc', devel_dir=devel_dir)
  File "/usr/local/lib/python2.7/site-packages/linkcheck/configuration/__init__.py", line 116, in get_share_file
    raise ValueError(msg)
ValueError: lccollection.qhc not found in ['/LinkChecker-9.3.data/data/doc/html', '/LinkChecker-9.3.data/data/share/linkchecker']; check your installation
```

The problem is that `get_share_dir()` call receives `/LinkChecker-9.3.data` as the first argument, constructing a path like `/LinkChecker-9.3.data/data/share/linkchecker` which does not exist and that failure to load the help file is fatal. Simply hard-coding `get_share_data` to `return '/usr/local/share/linkchecker'` avoids that problem and everything else appears to work.

**Comment by chrisfromredfin** [comment]
I'm not sure what the actual code fix is supposed to be, but +1 to this working for me.

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues if your issue still persists
