### ISSUE TITLE
'setup.py' requirement > python 2.7 not working

### ISSUE THREAD

**Issue by jeff1evesque** [wummel/linkchecker#623]
The following check does not work in [`setup.py`](https://github.com/wummel/linkchecker/blob/35eb30432ef7116cc93f2b33bdff7fc6a3aa0966/setup.py#L38-L40):

```python
...
if not (hasattr(sys, 'version_info') or
        sys.version_info < (2, 7, 0, 'final', 0)):
    raise SystemExit("This program requires Python 2.7 or later.")
...
```

I have installed linkchecker with python 2.6.6:

```bash
[vagrant@vagrant ~]$ sudo pip install linkchecker
Collecting linkchecker
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_
.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This
 prevents urllib3 from configuring SSL appropriately and may cause certain SSL c
onnections to fail. For more information, see https://urllib3.readthedocs.org/en
/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached LinkChecker-9.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): requests>=2.2.0 in /us
r/lib/python2.6/site-packages (from linkchecker)
Installing collected packages: linkchecker
  Running setup.py install for linkchecker
Successfully installed linkchecker-9.3
[vagrant@vagrant ~]$ sudo pip install linkchecker -r https://raw.githubusercont
ent.com/wummel/linkchecker/master/requirements.txt
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_
.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This
 prevents urllib3 from configuring SSL appropriately and may cause certain SSL c
onnections to fail. For more information, see https://urllib3.readthedocs.org/en
/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already satisfied (use --upgrade to upgrade): linkchecker in /usr/li
b64/python2.6/site-packages
Requirement already satisfied (use --upgrade to upgrade): requests>=2.2.0 in /us
r/lib/python2.6/site-packages (from -r https://raw.githubusercontent.com/wummel/
linkchecker/master/requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): argcomplete in /usr/li
b/python2.6/site-packages (from -r https://raw.githubusercontent.com/wummel/link
checker/master/requirements.txt (line 2))
[vagrant@vagrant ~]$ python -V
Python 2.6.6
```

Now, when I run linkchecker, it complains to me some packages are missing:

```bash
[vagrant@vagrant ~]$ linkchecker https://cnn.com
Traceback (most recent call last):
  File "/usr/bin/linkchecker", line 30, in <module>
    import linkcheck
  File "/usr/lib64/python2.6/site-packages/linkcheck/__init__.py", line 43, in <module>
    from .logconf import (
  File "/usr/lib64/python2.6/site-packages/linkcheck/logconf.py", line 22, in <module>
    from . import ansicolor
  File "/usr/lib64/python2.6/site-packages/linkcheck/ansicolor.py", line 62, in <module>
    from .fileutil import has_module, is_tty
  File "/usr/lib64/python2.6/site-packages/linkcheck/fileutil.py", line 26, in <module>
    import importlib
ImportError: No module named importlib
```

**Comment by peterjc** [comment]
Probably fixed by https://github.com/wummel/linkchecker/commit/c2ce810c3fb00b895a841a7be6b2e78c64e7b042

**Comment by jeff1evesque** [comment]
@peterjc It seems to be running:

``` bash
vagrant@vagrant-ubuntu-trusty-64:~$ sudo pip install linkchecker
[TRACE OMITTED DUE TO LENGTH]
vagrant@vagrant-ubuntu-trusty-64:~$ sudo linkchecker https://nccoe.nist.gov
WARNING 2016-07-22 10:03:29,111 MainThread Running as root user; dropping privil
eges by changing user to nobody.
INFO 2016-07-22 10:03:29,112 MainThread Checking intern URLs only; use --check-e
xtern to check extern URLs.
LinkChecker 9.3              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at http://wummel.github.io/linkchecker/
Write comments and bugs to https://github.com/wummel/linkchecker/issues
Support this project at http://wummel.github.io/linkchecker/donations.html

Start checking at 2016-07-22 10:03:29-004
10 threads active,    53 links queued,   18 links in   4 URLs checked, runtime 1
 seconds
10 threads active,   154 links queued,  100 links in  16 URLs checked, runtime 6
 seconds
10 threads active,   919 links queued,  728 links in  30 URLs checked, runtime 1
1 seconds
10 threads active,  1497 links queued, 1567 links in  44 URLs checked, runtime 1
6 seconds
10 threads active,  1638 links queued, 2161 links in  57 URLs checked, runtime 2
1 seconds
10 threads active,  1601 links queued, 2633 links in  69 URLs checked, runtime 2
6 seconds
10 threads active,  1496 links queued, 3276 links in  84 URLs checked, runtime 3
1 seconds
10 threads active,  1452 links queued, 3968 links in  95 URLs checked, runtime 3
6 seconds
10 threads active,  1308 links queued, 4534 links in 107 URLs checked, runtime 4
1 seconds
10 threads active,  1394 links queued, 4845 links in 120 URLs checked, runtime 4
6 seconds
10 threads active,  1339 links queued, 5382 links in 138 URLs checked, runtime 5
1 seconds
10 threads active,  1301 links queued, 6101 links in 148 URLs checked, runtime 5
6 seconds
10 threads active,  1358 links queued, 6987 links in 168 URLs checked, runtime 1
 minute, 1 seconds
10 threads active,  1327 links queued, 7527 links in 182 URLs checked, runtime 1
 minute, 6 seconds
10 threads active,  1223 links queued, 8284 links in 195 URLs checked, runtime 1
 minute, 11 seconds
10 threads active,  1230 links queued, 9359 links in 206 URLs checked, runtime 1
 minute, 16 seconds
10 threads active,  1295 links queued, 10460 links in 216 URLs checked, runtime
1 minute, 21 seconds
10 threads active,  1347 links queued, 11759 links in 226 URLs checked, runtime
1 minute, 26 seconds
10 threads active,  1306 links queued, 12620 links in 239 URLs checked, runtime
1 minute, 31 seconds
10 threads active,  1292 links queued, 12880 links in 253 URLs checked, runtime
1 minute, 36 seconds
10 threads active,  1261 links queued, 12911 links in 256 URLs checked, runtime
1 minute, 41 seconds
10 threads active,  1377 links queued, 14073 links in 269 URLs checked, runtime
1 minute, 46 seconds

URL        `news/retail-cybersecurity-workshop-kicks-new-nccoe-projects'
Name       `new projects at the NCCoE focused on the consumer-facing and retail
sector'
Parent URL https://nccoe.nist.gov/news/blog, line 239, col 363
Real URL   https://nccoe.nist.gov/news/news/retail-cybersecurity-workshop-kicks-
new-nccoe-projects
Check time 3.467 seconds
Result     Error: 404 Not Found
10 threads active,  1391 links queued, 15249 links in 288 URLs checked, runtime
1 minute, 51 seconds
10 threads active,  1406 links queued, 16040 links in 295 URLs checked, runtime
1 minute, 56 seconds
...
```

**Comment by jeff1evesque** [comment]
Is there a recommended syntax to pipe the linkchecking results into a file?  I'm going to try `sudo linkchecker https://some_url.com > linkchecker.txt 2>&1`.  It's going to take me about 20 minutes to run, before I know for sure, about the latter syntax.

**Comment by peterjc** [comment]
This is not related to the original bug report, but if the `-F` aka `--file-output` option isn't what you want, then the stdout/stderr direction looks sensible to me.

Also you probably don't need the `sudo` here, notice the warning:

```
vagrant@vagrant-ubuntu-trusty-64:~$ sudo linkchecker https://nccoe.nist.gov
WARNING 2016-07-22 10:03:29,111 MainThread Running as root user; dropping privileges by changing user to nobody.
...
```

Try just `linkchecker https://nccoe.nist.gov` instead.

**Comment by jeff1evesque** [comment]
Everything works, thank you!
