### ISSUE TITLE
LinkChecker is not working

### ISSUE THREAD

**Issue by OvaisAlam** [wummel/linkchecker#628]
Hello,
The LinkChecker is not working.
When closed, it gives a message to see the log (which is pasted in this issue).

Using LinkChecker 9.3 (GUI) and Python 2.7.11 on Windows 7.
* I have used the installer present on your website to install LC.

********** Oops, I did it again. *************

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/wummel/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

Traceback (most recent call last):
  File "linkcheck\director\checker.pyo", line 104, in check_url
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\director\checker.py
    -- code not available --
  File "linkcheck\director\checker.pyo", line 120, in check_url_data
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\director\checker.py
    -- code not available --
  File "linkcheck\director\checker.pyo", line 52, in check_url
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\director\checker.py
    -- code not available --
  File "linkcheck\checker\urlbase.pyo", line 424, in check
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\checker\urlbase.py
    -- code not available --
  File "linkcheck\checker\urlbase.pyo", line 442, in local_check
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\checker\urlbase.py
    -- code not available --
  File "linkcheck\checker\httpurl.pyo", line 128, in check_connection
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\checker\httpurl.py
    -- code not available --
  File "linkcheck\checker\httpurl.pyo", line 66, in allows_robots
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\checker\httpurl.py
    -- code not available --
  File "linkcheck\cache\robots_txt.pyo", line 49, in allows_url
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\cache\robots_txt.py
    -- code not available --
  File "linkcheck\cache\robots_txt.pyo", line 62, in _allows_url
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\cache\robots_txt.py
    -- code not available --
AttributeError: 'HttpUrl' object has no attribute 'proxy_type'
System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
Requests: 2.2.1
Qt: 4.8.6 / PyQt: 4.11
Modules: QScintilla, Sqlite
Local time: 2015-12-09 16:06:13+005
sys.argv: ['C:\\Program Files (x86)\\LinkChecker\\linkchecker-gui.exe']
Default locale: ('en', 'cp1252')

**Comment by jpfreire** [comment]
Mine was a proxy issue... message should be clear.

**Comment by OvaisAlam** [comment]
@jpfreire <br>
I am sorry, I didn't got you.

**Comment by jpfreire** [comment]
I had the same issue you found, but mine was a proxy problem. 
LinkChecker should more clear about that.
It was not an installation, nor file access permission issue, as it may seem because most of messages says "couldn't find file, trying this instead"
As per last message: AttributeError: 'HttpUrl' object has no attribute 'proxy_type'
worked things out for me.

**Comment by OvaisAlam** [comment]
Thank you for replying!

How did you fix that proxy error?
*I also working behind a proxy.

**Comment by invincible007** [comment]
did you get a solution to this ?

**Comment by OvaisAlam** [comment]
No, I was unable to find any solution.

**Comment by jomarthomas-zz** [comment]
Any updates on this issue ?
