### ISSUE TITLE
Linkchecker tells me to report this

### ISSUE THREAD

**Issue by gorgabal** [wummel/linkchecker#629]
➜  ~  linkchecker https://www.tni.org/en           
INFO 2015-12-14 13:41:27,425 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 9.3              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at http://wummel.github.io/linkchecker/
Write comments and bugs to https://github.com/wummel/linkchecker/issues
Support this project at http://wummel.github.io/linkchecker/donations.html

Start checking at 2015-12-14 13:41:27+002

********** Oops, I did it again. *************

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/wummel/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 104, in check_url

Statistics:
Downloaded: 0B.
No statistics available since no URLs were checked.

That's it.     line: self.check_url_data(url_data)0 links
     locals:in 0 URLs
 checked.       self = <local> <Checker(CheckThread-https://www.tni.org/en, started 140398921176832)>
0 warnings found      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-https://www.tni.org/en, started 140398921176832)>>
.       url_data = <local> <https link, base_url=u'https://www.tni.org/en', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://www.tni.org/en>
0 errors found  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 120, in check_url_data
.
Stopped checking at 2015-12-14 13:41:27+002 (0.26 seconds)
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x7fb12f4d4b90>
      url_data = <local> <https link, base_url=u'https://www.tni.org/en', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://www.tni.org/en>
      self = <local> <Checker(CheckThread-https://www.tni.org/en, started 140398921176832)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x7fb12eda9ed0>
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 52, in check_url
    line: url_data.check()
    locals:
      url_data = <local> <https link, base_url=u'https://www.tni.org/en', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://www.tni.org/en>
      url_data.check = <local> <bound method HttpUrl.check of <https link, base_url=u'https://www.tni.org/en', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://www.tni.org/en>>
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 424, in check
    line: self.local_check()
    locals:
      self = <local> <https link, base_url=u'https://www.tni.org/en', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://www.tni.org/en>
      self.local_check = <local> <bound method HttpUrl.local_check of <https link, base_url=u'https://www.tni.org/en', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://www.tni.org/en>>
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 442, in local_check
    line: self.check_connection()
    locals:
      self = <local> <https link, base_url=u'https://www.tni.org/en', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://www.tni.org/en>
      self.check_connection = <local> <bound method HttpUrl.check_connection of <https link, base_url=u'https://www.tni.org/en', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://www.tni.org/en>>
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 135, in check_connection
    line: self.send_request(request)
    locals:
      self = <local> <https link, base_url=u'https://www.tni.org/en', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://www.tni.org/en>
      self.send_request = <local> <bound method HttpUrl.send_request of <https link, base_url=u'https://www.tni.org/en', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://www.tni.org/en>>
      request = <local> <PreparedRequest [GET]>
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 165, in send_request
    line: self._send_request(request, **kwargs)
    locals:
      self = <local> <https link, base_url=u'https://www.tni.org/en', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://www.tni.org/en>
      self._send_request = <local> <bound method HttpUrl._send_request of <https link, base_url=u'https://www.tni.org/en', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://www.tni.org/en>>
      request = <local> <PreparedRequest [GET]>
      kwargs = <local> {'timeout': 60, 'stream': True, 'verify': True, 'allow_redirects': False}
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 172, in _send_request
    line: self._add_ssl_info()
    locals:
      self = <local> <https link, base_url=u'https://www.tni.org/en', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://www.tni.org/en>
      self._add_ssl_info = <local> <bound method HttpUrl._add_ssl_info of <https link, base_url=u'https://www.tni.org/en', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://www.tni.org/en>>
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 199, in _add_ssl_info
    line: self.ssl_cert = httputil.x509_to_dict(cert)
    locals:
      self = <local> <https link, base_url=u'https://www.tni.org/en', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://www.tni.org/en>
      self.ssl_cert = <local> None
      httputil = <global> <module 'linkcheck.httputil' from '/usr/lib/python2.7/dist-packages/linkcheck/httputil.pyc'>
      httputil.x509_to_dict = <global> <function x509_to_dict at 0x7fb12f7eee60>
      cert = <local> <OpenSSL.crypto.X509 object at 0x7fb1284e7990>
  File "/usr/lib/python2.7/dist-packages/linkcheck/httputil.py", line 35, in x509_to_dict
    line: from requests.packages.urllib3.contrib.pyopenssl import get_subj_alt_name
    locals:
      requests = <not found>
      requests.packages = <not found>
      requests.packages.urllib3 = <not found>
      requests.packages.urllib3.contrib = <not found>
      requests.packages.urllib3.contrib.pyopenssl = <not found>
      get_subj_alt_name = <not found>
ImportError: cannot import name get_subj_alt_name
System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Requests: 2.4.3
Qt: 4.8.6 / PyQt: 4.11.2
Modules: QScintilla, Sqlite, Gconf
Local time: 2015-12-14 13:41:27+002
sys.argv: ['/usr/bin/linkchecker', 'https://www.tni.org/en']
LANGUAGE = 'en_US:en'
LC_CTYPE = 'en_US.UTF-8'
LANG = 'en_US.UTF-8'
Default locale: ('en', 'UTF-8')

 ******** LinkChecker internal error, over and out ********
WARNING 2015-12-14 13:41:27,763 CheckThread-https://www.tni.org/en internal error occurred

**Comment by anarcat** [comment]
this is fixed in #656

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues if your issue still persists
