### ISSUE TITLE
Proxy Issue: "AttributeError: 'HttpUrl' object has no attribute 'proxy_type'"

### ISSUE THREAD

**Issue by Alex1593** [wummel/linkchecker#639]
Seems that issue https://github.com/wummel/linkchecker/issues/555 appears again:
I'm using the LinkChecker via windows command line and it worked correctly before I've initialized "**http_proxy**" and "**https_proxy**" environment variables with the required proxy address.

Traceback (most recent call last):
  File "linkcheck\director\checker.pyo", line 104, in check_url
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChec
er\library.zip\linkcheck\director\checker.py
    -- code not available --
  File "linkcheck\director\checker.pyo", line 120, in check_url_data
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChec
er\library.zip\linkcheck\director\checker.py
    -- code not available --
  File "linkcheck\director\checker.pyo", line 52, in check_url
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChec
er\library.zip\linkcheck\director\checker.py
    -- code not available --
  File "linkcheck\checker\urlbase.pyo", line 424, in check
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChec
er\library.zip\linkcheck\checker\urlbase.py
    -- code not available --
  File "linkcheck\checker\urlbase.pyo", line 442, in local_check
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChec
er\library.zip\linkcheck\checker\urlbase.py
    -- code not available --
  File "linkcheck\checker\httpurl.pyo", line 128, in check_connection
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChec
er\library.zip\linkcheck\checker\httpurl.py
    -- code not available --
  File "linkcheck\checker\httpurl.pyo", line 66, in allows_robots
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChec
er\library.zip\linkcheck\checker\httpurl.py
    -- code not available --
  File "linkcheck\cache\robots_txt.pyo", line 49, in allows_url
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChec
er\library.zip\linkcheck\cache\robots_txt.py
    -- code not available --
  File "linkcheck\cache\robots_txt.pyo", line 62, in _allows_url
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChec
er\library.zip\linkcheck\cache\robots_txt.py
    -- code not available --
AttributeError: 'HttpUrl' object has no attribute 'proxy_type'
System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on wi
32
Requests: 2.2.1
Qt: 4.8.6 / PyQt: 4.11
Modules: QScintilla, Sqlite
Local time: 2016-02-24 12:55:57+003
sys.argv: ['linkchecker.exe', '--threads=10', '--timeout=1800', '--user-agent=M
zilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome
48.0.2564.103 Safari/537.36',  'http://mysite.com/', '--file-output=html/test
.html', '--debug=cmdline', '--check-extern']
http_proxy = 'http://10.5.0.1:2233/'
Default locale: ('en', 'cp1252')

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues if your issue still persists
