### ISSUE TITLE
[windows 9.3]options>Configration file crashed

### ISSUE THREAD

**Issue by sssnnnbbb** [wummel/linkchecker#641]
can't open Configration file. 

below error dialog.

---------------------------------------

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/wummel/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

Traceback (most recent call last):
  File "linkcheck\gui\options.pyo", line 61, in edit_user_config
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\gui\options.py
    -- code not available --
  File "linkcheck\gui\options.pyo", line 92, in start_editor
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\gui\options.py
    -- code not available --
  File "linkcheck\gui\editor.pyo", line 175, in load
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\gui\editor.py
    -- code not available --
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-15: ordinal not in range(128)
System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
Requests: 2.2.1
Qt: 4.8.6 / PyQt: 4.11
Modules: QScintilla, Sqlite
Local time: 2016-03-23 17:38:37+009
sys.argv: ['C:\\Program Files (x86)\\LinkChecker\\linkchecker-gui.exe']
Default locale: ('ja', 'cp932')

**Comment by sssnnnbbb** [comment]
Cause was found

If the user name is the 2 bytes , the file path has been garbled .

<img src="https://www.evernote.com/shard/s16/sh/9ab8b5a8-f44a-4b18-9d2f-68edb249170d/1c26518659053a890c32d57340b19e7d/res/b6aed68c-b69e-4490-b8e9-32880590a617/skitch.png">


Is there a way to solve ?

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues if your issue still persists
