### ISSUE TITLE
'module' object has no attribute 'warning'

### ISSUE THREAD

**Issue by cswarth** [wummel/linkchecker#652]
After working around the naive and broken version check of the `requests` module, linkcheck now barfs up a fatal AttributeError - `'module' object has no attribute 'warning'`

The offending lines are,

```
linkcheck/htmlutil/formsearch.py:74:                    log.warning(LOG_CHECK, "nameless form input %s" % attrs)
linkcheck/htmlutil/formsearch.py:78:                log.warning(LOG_CHECK, "formless input´%s" % attrs)
```

It's `log.warn`, not `log.warning`

```
$ linkchecker -t 1 --user admin -p --ignore-url='.*logout.*' -v http://stoat:8000/
INFO 2016-05-10 11:37:30,217 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
Enter LinkChecker password for user admin at .+:
WARNING 2016-05-10 11:37:37,643 MainThread Error using login URL: 'module' object has no attribute 'warning'.
Traceback (most recent call last):
  File "/shared/silo_researcher/Matsen_F/MatsenGrp/working/cwarth/beast-si-scons/venv/bin/linkchecker", line 599, in <module>
    check_urls(aggregate)
  File "/shared/silo_researcher/Matsen_F/MatsenGrp/working/cwarth/beast-si-scons/venv/local/lib/python2.7/site-packages/linkcheck/director/__init__.py", line 34, in check_urls
    aggregate.visit_loginurl()
  File "/shared/silo_researcher/Matsen_F/MatsenGrp/working/cwarth/beast-si-scons/venv/local/lib/python2.7/site-packages/linkcheck/director/aggregator.py", line 86, in visit_loginurl
    encoding=response.encoding)
  File "/shared/silo_researcher/Matsen_F/MatsenGrp/working/cwarth/beast-si-scons/venv/local/lib/python2.7/site-packages/linkcheck/htmlutil/formsearch.py", line 101, in search_form
    parser.feed(content)
  File "/shared/silo_researcher/Matsen_F/MatsenGrp/working/cwarth/beast-si-scons/venv/local/lib/python2.7/site-packages/linkcheck/htmlutil/formsearch.py", line 77, in start_element
    log.warning(LOG_CHECK, "formless input´%s" % attrs)
AttributeError: 'module' object has no attribute 'warning'
```

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues if your issue still persists
