### ISSUE TITLE
Root error

### ISSUE THREAD

**Issue by gpgabriel** [wummel/linkchecker#667]
Hi,

I just installed linkchecker as described [here](https://github.com/wummel/linkchecker/blob/master/doc/install.txt):

`sudo pip install LinkChecker`

If I try to get the version as the root user, I get the following error:

`Traceback (most recent call last):
  File "/usr/bin/linkchecker", line 283, in <module>
    {"lognamelist": linkcheck.lognamelist})
AttributeError: 'module' object has no attribute 'lognamelist'`

For any other user, the version is displayed correctly:
`$ linkchecker --version`

`INFO 2016-06-29 17:54:33,487 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 9.3 released 16.7.2014
Copyright (C) 2000-2014 Bastian Kleineidam`

Any way to fix this ?

Thanks,
Gabriel

**Comment by gpgabriel** [comment]
Fixed, I think it was because of the environmental variables. I logged in as root using
`sudo su`

Once I started to use
`sudo su -`
it worked just fine.

For more details, check [this link.](https://wiki.archlinux.org/index.php/Su)

**Comment by gpgabriel** [comment]
Hi,

I still get the error even if I use 
`sudo su -`

`
Traceback (most recent call last):
  File "/usr/bin/linkchecker", line 283, in <module>
    {"lognamelist": linkcheck.lognamelist})
AttributeError: 'module' object has no attribute 'lognamelist'
`

Any ideas about how I could fix this ?

Thanks,
Gabriel

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues if your issue still persists
