### ISSUE TITLE
UnboundLocalError: local variable 'pat' referenced before assignment

### ISSUE THREAD

**Issue by rweil55** [wummel/linkchecker#674]
Click "Edit", "options", in the ignore URL box type  `*photo*,` Click "Close", "Start"
note the invalid regular expression.  `.*photpo.* does not error.`

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/wummel/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

Traceback (most recent call last):
  File "linkcheck\gui__init__.pyo", line 452, in on_controlButton_clicked
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\gui__init__.py
    -- code not available --
  File "linkcheck\gui__init__.pyo", line 438, in start
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\gui__init__.py
    -- code not available --
  File "linkcheck\gui__init__.pyo", line 473, in check
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\gui__init__.py
    -- code not available --
  File "linkcheck\gui__init__.pyo", line 282, in set_config
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\gui__init__.py
    -- code not available --
UnboundLocalError: local variable 'pat' referenced before assignment
System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
Requests: 2.2.1
Qt: 4.8.6 / PyQt: 4.11
Modules: QScintilla, Sqlite
Local time: 2016-07-30 08:08:20-004
sys.argv: ['C:\Program Files (x86)\LinkChecker\linkchecker-gui.exe']
Default locale: ('en', 'cp1252')

 *******\* LinkChecker internal error, over and out ********

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
**Also please close this issue** and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues
