### ISSUE TITLE
LinkChecker internal error

### ISSUE THREAD

**Issue by jsandeo** [wummel/linkchecker#702]
linkchecker -C -v -Fcsv/sdelsol-out.csv --ignore-url=\.jpe?g$ --ignore-url=\.png$ --ignore-url=\.gif$ --ignore-url=\.pdf$ http://www.sdelsol.com

********** Oops, I did it again. *************

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/wummel/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/task.py", line 29, in run
    line: self.run_checked()
    locals:
      self = <local> <Checker(CheckThread-http://www.sdelsol2.com/2016EV/Manuales/Manual_FactuSOL_2016.pdf, started -1259340992)>
      self.run_checked = <local> <bound method Checker.run_checked of <Checker(CheckThread-http://www.sdelsol2.com/2016EV/Manuales/Manual_FactuSOL_2016.pdf, started -1259340992)>>
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 48, in run_checked
    line: self.check_url()
    locals:
      self = <local> <Checker(CheckThread-http://www.sdelsol2.com/2016EV/Manuales/Manual_FactuSOL_2016.pdf, started -1259340992)>
      self.check_url = <local> <bound method Checker.check_url of <Checker(CheckThread-http://www.sdelsol2.com/2016EV/Manuales/Manual_FactuSOL_2016.pdf, started -1259340992)>>
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 56, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-http://www.sdelsol2.com/2016EV/Manuales/Manual_FactuSOL_2016.pdf, started -1259340992)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-http://www.sdelsol2.com/2016EV/Manuales/Manual_FactuSOL_2016.pdf, started -1259340992)>>
      url_data = <local> <http link, base_url=u'http://www.sdelsol2.com/2016EV/Manuales/Manual_FactuSOL_2016.pdf', parent_url=u'https://www.sdelsol.com/programa-facturacion-factusol/descubre.php', base_ref=None, recursion_level=4, url_connection=None, line=372, column=21, name=u'Manual de Usuario', anchor=u'', cache_key=...
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 71, in check_url_data
    line: url_data.check()
    locals:
      url_data = <local> <http link, base_url=u'http://www.sdelsol2.com/2016EV/Manuales/Manual_FactuSOL_2016.pdf', parent_url=u'https://www.sdelsol.com/programa-facturacion-factusol/descubre.php', base_ref=None, recursion_level=4, url_connection=None, line=372, column=21, name=u'Manual de Usuario', anchor=u'', cache_key=...
      url_data.check = <local> <bound method HttpUrl.check of <http link, base_url=u'http://www.sdelsol2.com/2016EV/Manuales/Manual_FactuSOL_2016.pdf', parent_url=u'https://www.sdelsol.com/programa-facturacion-factusol/descubre.php', base_ref=None, recursion_level=4, url_connection=None, line=372, column=21, name=u'Manual de U...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 489, in check
    line: self.local_check()
    locals:
      self = <local> <http link, base_url=u'http://www.sdelsol2.com/2016EV/Manuales/Manual_FactuSOL_2016.pdf', parent_url=u'https://www.sdelsol.com/programa-facturacion-factusol/descubre.php', base_ref=None, recursion_level=4, url_connection=None, line=372, column=21, name=u'Manual de Usuario', anchor=u'', cache_key=...
      self.local_check = <local> <bound method HttpUrl.local_check of <http link, base_url=u'http://www.sdelsol2.com/2016EV/Manuales/Manual_FactuSOL_2016.pdf', parent_url=u'https://www.sdelsol.com/programa-facturacion-factusol/descubre.php', base_ref=None, recursion_level=4, url_connection=None, line=372, column=21, name=u'Manua...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 521, in local_check
    line: assert not self.extern[1], 'checking strict extern URL'
    locals:
      self = <local> <http link, base_url=u'http://www.sdelsol2.com/2016EV/Manuales/Manual_FactuSOL_2016.pdf', parent_url=u'https://www.sdelsol.com/programa-facturacion-factusol/descubre.php', base_ref=None, recursion_level=4, url_connection=None, line=372, column=21, name=u'Manual de Usuario', anchor=u'', cache_key=...
      self.extern = <local> (1, True)
AssertionError: checking strict extern URL
System info:
LinkChecker 8.6
Python 2.7.6 (default, Oct 26 2016, 20:32:47) 
[GCC 4.8.4] on linux2
Qt: 4.8.6 / PyQt: 4.10.4
Modules: QScintilla, Sqlite, Gconf
Local time: 2017-01-13 20:16:05+002
sys.argv: ['/usr/bin/linkchecker', '-C', '-v', '-Fcsv/sdelsol-out.csv', '--ignore-url=.jpe?g$', '--ignore-url=.png$', '--ignore-url=.gif$', '--ignore-url=.pdf$', '--ignore-url=/Manuales/', 'http://www.sdelsol.com']
LANGUAGE = 'en'
LANG = 'en_US.UTF-8'
Default locale: ('en', 'UTF-8')

 ******** LinkChecker internal error, over and out ********

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
Also please close this issue and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues
