### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by chrismunoz** [wummel/linkchecker#719]
Filing this issue because it was requested of me by the program's error report. 

URL to be checked: `http://www.unce.unr.edu`

System information:
```Traceback (most recent call last):
  File "linkcheck\gui\__init__.pyo", line 452, in on_controlButton_clicked
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\gui\__init__.py
    -- code not available --
  File "linkcheck\gui\__init__.pyo", line 438, in start
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\gui\__init__.py
    -- code not available --
  File "linkcheck\gui\__init__.pyo", line 473, in check
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\gui\__init__.py
    -- code not available --
  File "linkcheck\gui\__init__.pyo", line 282, in set_config
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\gui\__init__.py
    -- code not available --
UnboundLocalError: local variable 'pat' referenced before assignment
System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
Requests: 2.2.1
Qt: 4.8.6 / PyQt: 4.11
Modules: QScintilla, Sqlite
Local time: 2017-06-07 12:32:35-007
sys.argv: ['C:\\Program Files (x86)\\LinkChecker\\linkchecker-gui.exe']
Default locale: ('en', 'cp1252')
```

This error happens when I add this filter in the Options panel under the "Ignore URLs matching one of these patterns" section: `*/xmlrpc.php*`
When this filter is in place, the LinkChecker cannot be run. I have to remove this filter before I can continue.

**Comment by dpalic** [comment]
this project is dead, please see: https://github.com/wummel/linkchecker/issues/708
