### ISSUE TITLE
Linkchecker internal error (apostrophe handling?)

### ISSUE THREAD

**Issue by chrishanretty** [wummel/linkchecker#732]
I'm reporting an internal error as requested. Full output is below. The error was repeated several times with pages on this site: the common factor seems to be the presence of an apostrophe in the url.

********** Oops, I did it again. *************

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/wummel/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 104, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-https://www.royalholloway.ac.uk/politicsandir/research/dec/blogs/articles/why-theresa-may%27s-gamble-at-the-polls-failed.aspx?nomobile=0, started 140621508146944)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-https://www.royalholloway.ac.uk/politicsandir/research/dec/blogs/articles/why-theresa-may%27s-gamble-at-the-polls-failed.aspx?nomobile=0, started 140621508146944)>>
      url_data = <local> <https link, base_url=u'?nomobile=0', parent_url=u'https://www.royalholloway.ac.uk/politicsandir/research/dec/blogs/articles/why-theresa-may%27s-gamble-at-the-polls-failed.aspx', base_ref=None, recursion_level=3, url_connection=None, line=613, column=49, page=0, name=u'Mobile site view', anchor=u...
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 120, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x7fe5007c7230>
      url_data = <local> <https link, base_url=u'?nomobile=0', parent_url=u'https://www.royalholloway.ac.uk/politicsandir/research/dec/blogs/articles/why-theresa-may%27s-gamble-at-the-polls-failed.aspx', base_ref=None, recursion_level=3, url_connection=None, line=613, column=49, page=0, name=u'Mobile site view', anchor=u...
      self = <local> <Checker(CheckThread-https://www.royalholloway.ac.uk/politicsandir/research/dec/blogs/articles/why-theresa-may%27s-gamble-at-the-polls-failed.aspx?nomobile=0, started 140621508146944)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x7fe501af9e50>
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 64, in check_url
    line: parser.parse_url(url_data)
    locals:
      parser = <global> <module 'linkcheck.parser' from '/usr/lib/python2.7/dist-packages/linkcheck/parser/__init__.pyc'>
      parser.parse_url = <global> <function parse_url at 0x7fe5007bf848>
      url_data = <local> <https link, base_url=u'?nomobile=0', parent_url=u'https://www.royalholloway.ac.uk/politicsandir/research/dec/blogs/articles/why-theresa-may%27s-gamble-at-the-polls-failed.aspx', base_ref=None, recursion_level=3, url_connection=None, line=613, column=49, page=0, name=u'Mobile site view', anchor=u...
  File "/usr/lib/python2.7/dist-packages/linkcheck/parser/__init__.py", line 39, in parse_url
    line: globals()[funcname](url_data)
    locals:
      globals = <builtin> <built-in function globals>
      funcname = <local> 'parse_html', len = 10
      url_data = <local> <https link, base_url=u'?nomobile=0', parent_url=u'https://www.royalholloway.ac.uk/politicsandir/research/dec/blogs/articles/why-theresa-may%27s-gamble-at-the-polls-failed.aspx', base_ref=None, recursion_level=3, url_connection=None, line=613, column=49, page=0, name=u'Mobile site view', anchor=u...
  File "/usr/lib/python2.7/dist-packages/linkcheck/parser/__init__.py", line 48, in parse_html
    line: find_links(url_data, url_data.add_url, linkparse.LinkTags)
    locals:
      find_links = <global> <function find_links at 0x7fe5007bfc80>
      url_data = <local> <https link, base_url=u'?nomobile=0', parent_url=u'https://www.royalholloway.ac.uk/politicsandir/research/dec/blogs/articles/why-theresa-may%27s-gamble-at-the-polls-failed.aspx', base_ref=None, recursion_level=3, url_connection=None, line=613, column=49, page=0, name=u'Mobile site view', anchor=u...
      url_data.add_url = <local> <bound method HttpUrl.add_url of <https link, base_url=u'?nomobile=0', parent_url=u'https://www.royalholloway.ac.uk/politicsandir/research/dec/blogs/articles/why-theresa-may%27s-gamble-at-the-polls-failed.aspx', base_ref=None, recursion_level=3, url_connection=None, line=613, column=49, page=0, n...
      linkparse = <global> <module 'linkcheck.htmlutil.linkparse' from '/usr/lib/python2.7/dist-packages/linkcheck/htmlutil/linkparse.pyc'>
      linkparse.LinkTags = <global> {'tr': [u'background'], 'q': [u'cite'], 'meta': [u'content', u'href'], 'isindex': [u'action'], 'track': [u'src'], 'applet': [u'archive', u'src'], 'object': [u'classid', u'data', u'archive', u'usemap', u'codebase'], None: [u'style', u'itemtype'], 'layer': [u'background', u'src'], 'html': [u'manife..., len = 35
  File "/usr/lib/python2.7/dist-packages/linkcheck/parser/__init__.py", line 126, in find_links
    line: parser.feed(url_data.get_content())
    locals:
      parser = <local> <linkcheck.HtmlParser.htmlsax.parser object at 0x7fe4cb190418>
      parser.feed = <local> <built-in method feed of linkcheck.HtmlParser.htmlsax.parser object at 0x7fe4cb190418>
      url_data = <local> <https link, base_url=u'?nomobile=0', parent_url=u'https://www.royalholloway.ac.uk/politicsandir/research/dec/blogs/articles/why-theresa-may%27s-gamble-at-the-polls-failed.aspx', base_ref=None, recursion_level=3, url_connection=None, line=613, column=49, page=0, name=u'Mobile site view', anchor=u...
      url_data.get_content = <local> <bound method HttpUrl.get_content of <https link, base_url=u'?nomobile=0', parent_url=u'https://www.royalholloway.ac.uk/politicsandir/research/dec/blogs/articles/why-theresa-may%27s-gamble-at-the-polls-failed.aspx', base_ref=None, recursion_level=3, url_connection=None, line=613, column=49, page=...
  File "/usr/lib/python2.7/dist-packages/linkcheck/htmlutil/linkparse.py", line 231, in start_element
    line: self.parse_tag(tag, attr, value, name, base)
    locals:
      self = <local> <linkcheck.htmlutil.linkparse.LinkFinder object at 0x7fe4dcec1910>
      self.parse_tag = <local> <bound method LinkFinder.parse_tag of <linkcheck.htmlutil.linkparse.LinkFinder object at 0x7fe4dcec1910>>
      tag = <local> u'link'
      attr = <local> u'href'
      value = <local> u'/siteelements/styles/100-system.css?version=2692258?version=2692258', len = 67
      name = <local> u''
      base = <local> u''
  File "/usr/lib/python2.7/dist-packages/linkcheck/htmlutil/linkparse.py", line 277, in parse_tag
    line: self.found_url(value, name, base)
    locals:
      self = <local> <linkcheck.htmlutil.linkparse.LinkFinder object at 0x7fe4dcec1910>
      self.found_url = <local> <bound method LinkFinder.found_url of <linkcheck.htmlutil.linkparse.LinkFinder object at 0x7fe4dcec1910>>
      value = <local> u'/siteelements/styles/100-system.css?version=2692258?version=2692258', len = 67
      name = <local> u''
      base = <local> u''
  File "/usr/lib/python2.7/dist-packages/linkcheck/htmlutil/linkparse.py", line 283, in found_url
    line: column=self.parser.last_column(), name=name, base=base)
    locals:
      column = <not found>
      self = <local> <linkcheck.htmlutil.linkparse.LinkFinder object at 0x7fe4dcec1910>
      self.parser = <local> <linkcheck.HtmlParser.htmlsax.parser object at 0x7fe4cb190418>
      self.parser.last_column = <local> <built-in method last_column of linkcheck.HtmlParser.htmlsax.parser object at 0x7fe4cb190418>
      name = <local> u''
      base = <local> u''
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 653, in add_url
    line: page=page, name=name, parent_content_type=self.content_type)
    locals:
      page = <local> 0
      name = <local> u''
      parent_content_type = <not found>
      self = <local> <https link, base_url=u'?nomobile=0', parent_url=u'https://www.royalholloway.ac.uk/politicsandir/research/dec/blogs/articles/why-theresa-may%27s-gamble-at-the-polls-failed.aspx', base_ref=None, recursion_level=3, url_connection=None, line=613, column=49, page=0, name=u'Mobile site view', anchor=u...
      self.content_type = <local> 'text/html', len = 9
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/__init__.py", line 125, in get_url_from
    line: line=line, column=column, page=page, name=name, extern=extern)
    locals:
      line = <local> 8
      column = <local> 422
      page = <local> 0
      name = <local> u''
      extern = <local> None
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 117, in __init__
    line: aggregate, line, column, page, name, url_encoding, extern)
    locals:
      aggregate = <local> <linkcheck.director.aggregator.Aggregate object at 0x7fe501af9610>
      line = <local> 8
      column = <local> 422
      page = <local> 0
      name = <local> u''
      url_encoding = <local> None
      extern = <local> None
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 157, in init
    line: "unquoted parent URL %r" % self.parent_url
    locals:
      self = <local> <None link, base_url=u'/siteelements/styles/100-system.css?version=2692258?version=2692258', parent_url=u"https://www.royalholloway.ac.uk/politicsandir/research/dec/blogs/articles/why-theresa-may's-gamble-at-the-polls-failed.aspx?478490430", base_ref=None, recursion_level=4, url_connection=None, ...
      self.parent_url = <local> u"https://www.royalholloway.ac.uk/politicsandir/research/dec/blogs/articles/why-theresa-may's-gamble-at-the-polls-failed.aspx?478490430", len = 133
AssertionError: unquoted parent URL u"https://www.royalholloway.ac.uk/politicsandir/research/dec/blogs/articles/why-theresa-may's-gamble-at-the-polls-failed.aspx?478490430"
System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Requests: 2.10.0
Modules: Sqlite
Local time: 2017-08-29 12:35:20+001
sys.argv: ['/usr/bin/linkchecker', 'https://www.royalholloway.ac.uk/politicsandir/home.aspx']
LANGUAGE = 'en_GB:en'
LANG = 'en_GB.UTF-8'
Default locale: ('en', 'UTF-8')

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
Also please close this issue and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues
