### ISSUE TITLE
Internal eror

### ISSUE THREAD

**Issue by ashleytao** [wummel/linkchecker#738]
Command I used: ['/home/taoa2/linkchecker/LinkChecker-9.3/bin/linkchecker', 'https://qa.ncbi.nlm.nih.gov/omim/276700', '-r1', '--no-robots', '-ohtml', '--check-extern', '--no-warning', '-Dall']

Traceback (most recent call last):
  File "/home/taoa2/linkchecker/LinkChecker-9.3/lib/python/LinkChecker-9.3-py2.7-linux-x86_64.egg/linkcheck/director/checker.py", line 104, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-https://qa.ncbi.nlm.nih.gov/omim/276700, started 140202563598080)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-https://qa.ncbi.nlm.nih.gov/omim/276700, started 140202563598080)>>
      url_data = <local> <https link, base_url=u'https://qa.ncbi.nlm.nih.gov/omim/276700', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://qa.ncbi.nlm.nih.gov/omim/276700>
  File "/home/taoa2/linkchecker/LinkChecker-9.3/lib/python/LinkChecker-9.3-py2.7-linux-x86_64.egg/linkcheck/director/checker.py", line 120, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x7f83795341b8>
      url_data = <local> <https link, base_url=u'https://qa.ncbi.nlm.nih.gov/omim/276700', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://qa.ncbi.nlm.nih.gov/omim/276700>
      self = <local> <Checker(CheckThread-https://qa.ncbi.nlm.nih.gov/omim/276700, started 140202563598080)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x7f8378fc2510>
  File "/home/taoa2/linkchecker/LinkChecker-9.3/lib/python/LinkChecker-9.3-py2.7-linux-x86_64.egg/linkcheck/director/checker.py", line 52, in check_url
    line: url_data.check()
    locals:
      url_data = <local> <https link, base_url=u'https://qa.ncbi.nlm.nih.gov/omim/276700', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://qa.ncbi.nlm.nih.gov/omim/276700>
      url_data.check = <local> <bound method HttpUrl.check of <https link, base_url=u'https://qa.ncbi.nlm.nih.gov/omim/276700', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://qa.ncbi.nlm.nih.gov/omim/276700>>
  File "/home/taoa2/linkchecker/LinkChecker-9.3/lib/python/LinkChecker-9.3-py2.7-linux-x86_64.egg/linkcheck/checker/urlbase.py", line 424, in check
    line: self.local_check()
    locals:
      self = <local> <https link, base_url=u'https://qa.ncbi.nlm.nih.gov/omim/276700', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://qa.ncbi.nlm.nih.gov/omim/276700>
      self.local_check = <local> <bound method HttpUrl.local_check of <https link, base_url=u'https://qa.ncbi.nlm.nih.gov/omim/276700', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://qa.ncbi.nlm.nih.gov/omim/276700>>
  File "/home/taoa2/linkchecker/LinkChecker-9.3/lib/python/LinkChecker-9.3-py2.7-linux-x86_64.egg/linkcheck/checker/urlbase.py", line 442, in local_check
    line: self.check_connection()
    locals:
      self = <local> <https link, base_url=u'https://qa.ncbi.nlm.nih.gov/omim/276700', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://qa.ncbi.nlm.nih.gov/omim/276700>
      self.check_connection = <local> <bound method HttpUrl.check_connection of <https link, base_url=u'https://qa.ncbi.nlm.nih.gov/omim/276700', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://qa.ncbi.nlm.nih.gov/omim/276700>>
  File "/home/taoa2/linkchecker/LinkChecker-9.3/lib/python/LinkChecker-9.3-py2.7-linux-x86_64.egg/linkcheck/checker/httpurl.py", line 136, in check_connection
    line: self.send_request(request)
    locals:
      self = <local> <https link, base_url=u'https://qa.ncbi.nlm.nih.gov/omim/276700', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://qa.ncbi.nlm.nih.gov/omim/276700>
      self.send_request = <local> <bound method HttpUrl.send_request of <https link, base_url=u'https://qa.ncbi.nlm.nih.gov/omim/276700', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://qa.ncbi.nlm.nih.gov/omim/276700>>
      request = <local> <PreparedRequest [GET]>
  File "/home/taoa2/linkchecker/LinkChecker-9.3/lib/python/LinkChecker-9.3-py2.7-linux-x86_64.egg/linkcheck/checker/httpurl.py", line 167, in send_request
    line: self._send_request(request, **kwargs)
    locals:
      self = <local> <https link, base_url=u'https://qa.ncbi.nlm.nih.gov/omim/276700', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://qa.ncbi.nlm.nih.gov/omim/276700>
      self._send_request = <local> <bound method HttpUrl._send_request of <https link, base_url=u'https://qa.ncbi.nlm.nih.gov/omim/276700', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://qa.ncbi.nlm.nih.gov/omim/276700>>
      request = <local> <PreparedRequest [GET]>
      kwargs = <local> {'verify': True, 'timeout': 60, 'stream': True, 'allow_redirects': True}
  File "/home/taoa2/linkchecker/LinkChecker-9.3/lib/python/LinkChecker-9.3-py2.7-linux-x86_64.egg/linkcheck/checker/httpurl.py", line 174, in _send_request
    line: self._add_ssl_info()
    locals:
      self = <local> <https link, base_url=u'https://qa.ncbi.nlm.nih.gov/omim/276700', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://qa.ncbi.nlm.nih.gov/omim/276700>
      self._add_ssl_info = <local> <bound method HttpUrl._add_ssl_info of <https link, base_url=u'https://qa.ncbi.nlm.nih.gov/omim/276700', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://qa.ncbi.nlm.nih.gov/omim/276700>>
  File "/home/taoa2/linkchecker/LinkChecker-9.3/lib/python/LinkChecker-9.3-py2.7-linux-x86_64.egg/linkcheck/checker/httpurl.py", line 200, in _add_ssl_info
    line: cert = sock.connection.get_peer_certificate()
    locals:
      cert = <not found>
      sock = <local> <socket._socketobject object at 0x7f837900dde0>
      sock.connection = <local> !AttributeError: '_socketobject' object has no attribute 'connection'
      sock.connection.get_peer_certificate = <local> !AttributeError: '_socketobject' object has no attribute 'connection'
AttributeError: '_socketobject' object has no attribute 'connection'
System info:
LinkChecker 9.4
Released on: xx.xx.xxxx
Python 2.7.12 (default, Sep 20 2016, 14:05:04) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
PYTHONPATH = '/home/taoa2/bin/lib/python:.:/home/taoa2/qaadmin/apps:/home/taoa2/linkchecker/LinkChecker-9.3/lib/python'
Requests: 2.13.0
Modules: Sqlite
Local time: 2017-10-02 11:38:17-004
sys.argv: ['/home/taoa2/linkchecker/LinkChecker-9.3/bin/linkchecker', 'https://qa.ncbi.nlm.nih.gov/omim/276700', '-r1', '--no-robots', '-ohtml', '--check-extern', '--no-warning', '-Dall']
LC_ALL = 'en_GB.UTF-8'
LANG = 'en_US'
Default locale: ('en', 'UTF-8')

 ******** LinkChecker internal error, over and out ********

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
Also please close this issue and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues
