### ISSUE TITLE
internal error in command line client

### ISSUE THREAD

**Issue by sam-s** [wummel/linkchecker#740]
```
Traceback (most recent call last):
  File "/Users/sds/.virtualenvs/local/lib/python2.7/site-packages/linkcheck/director/checker.py", line 104, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-https://sourceforge.net/p/clisp/bugs/, started 123145531539456)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-https://sourceforge.net/p/clisp/bugs/, started 123145531539456)>>
      url_data = <local> <https link, base_url=u'https://sourceforge.net/p/clisp/bugs/', parent_url=u'https://clisp.sourceforge.io/beta/impnotes/clisp.html#bugs', base_ref=None, recursion_level=2, url_connection=None, line=308, column=2, page=0, name=u'SourceForge bug tracker', anchor=u'', cache_url=https://sourceforge.n...
  File "/Users/sds/.virtualenvs/local/lib/python2.7/site-packages/linkcheck/director/checker.py", line 120, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x105bee050>
      url_data = <local> <https link, base_url=u'https://sourceforge.net/p/clisp/bugs/', parent_url=u'https://clisp.sourceforge.io/beta/impnotes/clisp.html#bugs', base_ref=None, recursion_level=2, url_connection=None, line=308, column=2, page=0, name=u'SourceForge bug tracker', anchor=u'', cache_url=https://sourceforge.n...
      self = <local> <Checker(CheckThread-https://sourceforge.net/p/clisp/bugs/, started 123145531539456)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x105d33350>
  File "/Users/sds/.virtualenvs/local/lib/python2.7/site-packages/linkcheck/director/checker.py", line 52, in check_url
    line: url_data.check()
    locals:
      url_data = <local> <https link, base_url=u'https://sourceforge.net/p/clisp/bugs/', parent_url=u'https://clisp.sourceforge.io/beta/impnotes/clisp.html#bugs', base_ref=None, recursion_level=2, url_connection=None, line=308, column=2, page=0, name=u'SourceForge bug tracker', anchor=u'', cache_url=https://sourceforge.n...
      url_data.check = <local> <bound method HttpUrl.check of <https link, base_url=u'https://sourceforge.net/p/clisp/bugs/', parent_url=u'https://clisp.sourceforge.io/beta/impnotes/clisp.html#bugs', base_ref=None, recursion_level=2, url_connection=None, line=308, column=2, page=0, name=u'SourceForge bug tracker', anchor=u'', ...
  File "/Users/sds/.virtualenvs/local/lib/python2.7/site-packages/linkcheck/checker/urlbase.py", line 424, in check
    line: self.local_check()
    locals:
      self = <local> <https link, base_url=u'https://sourceforge.net/p/clisp/bugs/', parent_url=u'https://clisp.sourceforge.io/beta/impnotes/clisp.html#bugs', base_ref=None, recursion_level=2, url_connection=None, line=308, column=2, page=0, name=u'SourceForge bug tracker', anchor=u'', cache_url=https://sourceforge.n...
      self.local_check = <local> <bound method HttpUrl.local_check of <https link, base_url=u'https://sourceforge.net/p/clisp/bugs/', parent_url=u'https://clisp.sourceforge.io/beta/impnotes/clisp.html#bugs', base_ref=None, recursion_level=2, url_connection=None, line=308, column=2, page=0, name=u'SourceForge bug tracker', anchor...
  File "/Users/sds/.virtualenvs/local/lib/python2.7/site-packages/linkcheck/checker/urlbase.py", line 442, in local_check
    line: self.check_connection()
    locals:
      self = <local> <https link, base_url=u'https://sourceforge.net/p/clisp/bugs/', parent_url=u'https://clisp.sourceforge.io/beta/impnotes/clisp.html#bugs', base_ref=None, recursion_level=2, url_connection=None, line=308, column=2, page=0, name=u'SourceForge bug tracker', anchor=u'', cache_url=https://sourceforge.n...
      self.check_connection = <local> <bound method HttpUrl.check_connection of <https link, base_url=u'https://sourceforge.net/p/clisp/bugs/', parent_url=u'https://clisp.sourceforge.io/beta/impnotes/clisp.html#bugs', base_ref=None, recursion_level=2, url_connection=None, line=308, column=2, page=0, name=u'SourceForge bug tracker', a...
  File "/Users/sds/.virtualenvs/local/lib/python2.7/site-packages/linkcheck/checker/httpurl.py", line 135, in check_connection
    line: self.send_request(request)
    locals:
      self = <local> <https link, base_url=u'https://sourceforge.net/p/clisp/bugs/', parent_url=u'https://clisp.sourceforge.io/beta/impnotes/clisp.html#bugs', base_ref=None, recursion_level=2, url_connection=None, line=308, column=2, page=0, name=u'SourceForge bug tracker', anchor=u'', cache_url=https://sourceforge.n...
      self.send_request = <local> <bound method HttpUrl.send_request of <https link, base_url=u'https://sourceforge.net/p/clisp/bugs/', parent_url=u'https://clisp.sourceforge.io/beta/impnotes/clisp.html#bugs', base_ref=None, recursion_level=2, url_connection=None, line=308, column=2, page=0, name=u'SourceForge bug tracker', ancho...
      request = <local> <PreparedRequest [GET]>
  File "/Users/sds/.virtualenvs/local/lib/python2.7/site-packages/linkcheck/checker/httpurl.py", line 165, in send_request
    line: self._send_request(request, **kwargs)
    locals:
      self = <local> <https link, base_url=u'https://sourceforge.net/p/clisp/bugs/', parent_url=u'https://clisp.sourceforge.io/beta/impnotes/clisp.html#bugs', base_ref=None, recursion_level=2, url_connection=None, line=308, column=2, page=0, name=u'SourceForge bug tracker', anchor=u'', cache_url=https://sourceforge.n...
      self._send_request = <local> <bound method HttpUrl._send_request of <https link, base_url=u'https://sourceforge.net/p/clisp/bugs/', parent_url=u'https://clisp.sourceforge.io/beta/impnotes/clisp.html#bugs', base_ref=None, recursion_level=2, url_connection=None, line=308, column=2, page=0, name=u'SourceForge bug tracker', anch...
      request = <local> <PreparedRequest [GET]>
      kwargs = <local> {'verify': True, 'allow_redirects': False, 'timeout': 60, 'stream': True}
  File "/Users/sds/.virtualenvs/local/lib/python2.7/site-packages/linkcheck/checker/httpurl.py", line 172, in _send_request
    line: self._add_ssl_info()
    locals:
      self = <local> <https link, base_url=u'https://sourceforge.net/p/clisp/bugs/', parent_url=u'https://clisp.sourceforge.io/beta/impnotes/clisp.html#bugs', base_ref=None, recursion_level=2, url_connection=None, line=308, column=2, page=0, name=u'SourceForge bug tracker', anchor=u'', cache_url=https://sourceforge.n...
      self._add_ssl_info = <local> <bound method HttpUrl._add_ssl_info of <https link, base_url=u'https://sourceforge.net/p/clisp/bugs/', parent_url=u'https://clisp.sourceforge.io/beta/impnotes/clisp.html#bugs', base_ref=None, recursion_level=2, url_connection=None, line=308, column=2, page=0, name=u'SourceForge bug tracker', anch...
  File "/Users/sds/.virtualenvs/local/lib/python2.7/site-packages/linkcheck/checker/httpurl.py", line 193, in _add_ssl_info
    line: sock = self._get_ssl_sock()
    locals:
      sock = <not found>
      self = <local> <https link, base_url=u'https://sourceforge.net/p/clisp/bugs/', parent_url=u'https://clisp.sourceforge.io/beta/impnotes/clisp.html#bugs', base_ref=None, recursion_level=2, url_connection=None, line=308, column=2, page=0, name=u'SourceForge bug tracker', anchor=u'', cache_url=https://sourceforge.n...
      self._get_ssl_sock = <local> <bound method HttpUrl._get_ssl_sock of <https link, base_url=u'https://sourceforge.net/p/clisp/bugs/', parent_url=u'https://clisp.sourceforge.io/beta/impnotes/clisp.html#bugs', base_ref=None, recursion_level=2, url_connection=None, line=308, column=2, page=0, name=u'SourceForge bug tracker', anch...
  File "/Users/sds/.virtualenvs/local/lib/python2.7/site-packages/linkcheck/checker/httpurl.py", line 187, in _get_ssl_sock
    line: raw_connection.connect()
    locals:
      raw_connection = <local> <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1094c76d0>
      raw_connection.connect = <local> <bound method VerifiedHTTPSConnection.connect of <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1094c76d0>>
  File "/Users/sds/.virtualenvs/local/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 217, in connect
    line: conn = self._new_conn()
    locals:
      conn = <not found>
      self = <local> <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1094c76d0>
      self._new_conn = <local> <bound method VerifiedHTTPSConnection._new_conn of <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1094c76d0>>
  File "/Users/sds/.virtualenvs/local/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 146, in _new_conn
    line: self, "Failed to establish a new connection: %s" % e)
    locals:
      self = <local> <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1094c76d0>
      e = <local> gaierror(8, 'nodename nor servname provided, or not known')
NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1094c76d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known
System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.14 (default, Sep 25 2017, 09:53:22) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Requests: 2.9.2
Modules: Sqlite
Local time: 2017-10-27 13:21:10-004
sys.argv: ['/Users/sds/.virtualenvs/local/bin/linkchecker', '--check-extern', '-F', 'blacklist', '-F', 'csv', '-F', 'text', '-F', 'none', '-F', 'dot', '-F', 'gml', 'https://clisp.sourceforge.io/beta/impnotes/']
LANG = 'en_US.UTF-8'
Default locale: ('en', 'UTF-8')
```

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker 
for more details please see: #708
Also please close this issue and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues
