### ISSUE TITLE
internal error in LinkChecker

### ISSUE THREAD

**Issue by iphydf** [wummel/linkchecker#743]
```
********** Oops, I did it again. *************
You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/wummel/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below
When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"
Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/task.py", line 29, in run
    line: self.run_checked()
    locals:
      self = <local> <Checker(CheckThread-https://msgpack.org/, started 47518985987840)>
      self.run_checked = <local> <bound method Checker.run_checked of <Checker(CheckThread-https://msgpack.org/, started 47518985987840)>>
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 48, in run_checked
    line: self.check_url()
    locals:
      self = <local> <Checker(CheckThread-https://msgpack.org/, started 47518985987840)>
      self.check_url = <local> <bound method Checker.check_url of <Checker(CheckThread-https://msgpack.org/, started 47518985987840)>>
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 56, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-https://msgpack.org/, started 47518985987840)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-https://msgpack.org/, started 47518985987840)>>
      url_data = <local> <https link, base_url=u'https://msgpack.org/', parent_url=u'file:///home/travis/build/TokTok/website/toktok-site/spec.html', base_ref=None, recursion_level=3, url_connection=None, line=4768, column=70, name=u'MessagePack', anchor=u'', cache_key=u'https://msgpack.org/'>
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 71, in check_url_data
    line: url_data.check()
    locals:
      url_data = <local> <https link, base_url=u'https://msgpack.org/', parent_url=u'file:///home/travis/build/TokTok/website/toktok-site/spec.html', base_ref=None, recursion_level=3, url_connection=None, line=4768, column=70, name=u'MessagePack', anchor=u'', cache_key=u'https://msgpack.org/'>
      url_data.check = <local> <bound method HttpsUrl.check of <https link, base_url=u'https://msgpack.org/', parent_url=u'file:///home/travis/build/TokTok/website/toktok-site/spec.html', base_ref=None, recursion_level=3, url_connection=None, line=4768, column=70, name=u'MessagePack', anchor=u'', cache_key=u'https://msgpack.or...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 489, in check
    line: self.local_check()
    locals:
      self = <local> <https link, base_url=u'https://msgpack.org/', parent_url=u'file:///home/travis/build/TokTok/website/toktok-site/spec.html', base_ref=None, recursion_level=3, url_connection=None, line=4768, column=70, name=u'MessagePack', anchor=u'', cache_key=u'https://msgpack.org/'>
      self.local_check = <local> <bound method HttpsUrl.local_check of <https link, base_url=u'https://msgpack.org/', parent_url=u'file:///home/travis/build/TokTok/website/toktok-site/spec.html', base_ref=None, recursion_level=3, url_connection=None, line=4768, column=70, name=u'MessagePack', anchor=u'', cache_key=u'https://msgp...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpsurl.py", line 36, in local_check
    line: super(HttpsUrl, self).local_check()
    locals:
      super = <builtin> <type 'super'>
      HttpsUrl = <global> <class 'linkcheck.checker.httpsurl.HttpsUrl'>
      self = <local> <https link, base_url=u'https://msgpack.org/', parent_url=u'file:///home/travis/build/TokTok/website/toktok-site/spec.html', base_ref=None, recursion_level=3, url_connection=None, line=4768, column=70, name=u'MessagePack', anchor=u'', cache_key=u'https://msgpack.org/'>
      local_check = <not found>
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 521, in local_check
    line: assert not self.extern[1], 'checking strict extern URL'
    locals:
      self = <local> <https link, base_url=u'https://msgpack.org/', parent_url=u'file:///home/travis/build/TokTok/website/toktok-site/spec.html', base_ref=None, recursion_level=3, url_connection=None, line=4768, column=70, name=u'MessagePack', anchor=u'', cache_key=u'https://msgpack.org/'>
      self.extern = <local> (1, True)
AssertionError: checking strict extern URL
System info:
LinkChecker 8.6
Python 2.7.6 (default, Nov 23 2017, 15:49:48) 
[GCC 4.8.4] on linux2
Modules: Sqlite
Local time: 2017-12-29 23:39:49+000
sys.argv: ['/usr/bin/linkchecker', '--ignore-url', 'https://toktok.ltd.*', '--ignore-url', 'https://msgpack.org.*', '--ignore-url', 'https://travis-ci.org.*', '--ignore-url', 'irc://.*', '--ignore-url', '^javascript:', 'toktok-site']
LC_ALL = 'en_US.UTF-8'
LANG = 'en_US.UTF-8'
Default locale: ('en', 'UTF-8')
 ******** LinkChecker internal error, over and out ********
WARNING CheckThread-https://msgpack.org/ internal error occurred
```

**Comment by gl00ten** [comment]
https://github.com/linkcheck/linkchecker <- new project, this one is dead it seems
