### ISSUE TITLE
Unable to `sudo pip install LinkChecker` on Arch Linux

### ISSUE THREAD

**Issue by Compro-Prasad** [wummel/linkchecker#753]
```
Collecting LinkChecker
  Downloading https://files.pythonhosted.org/packages/43/59/31baf302792306bde0825e8631a74c7f668bc47b3748fc4471c281885bb6/LinkChecker-9.3.tar.gz (719kB)
    100% |████████████████████████████████| 727kB 145kB/s 
Requirement already satisfied: requests>=2.2.0 in /usr/lib/python3.6/site-packages (from LinkChecker) (2.19.1)
Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3.6/site-packages (from requests>=2.2.0->LinkChecker) (3.0.4)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.6/site-packages (from requests>=2.2.0->LinkChecker) (2.7)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.6/site-packages (from requests>=2.2.0->LinkChecker) (1.23)
Building wheels for collected packages: LinkChecker
  Running setup.py bdist_wheel for LinkChecker ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-i5f3magc/LinkChecker/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-s668buuz --python-tag cp36:
  creating /tmp/pip-install-i5f3magc/LinkChecker/_LinkChecker_configdata.py
  running bdist_wheel
  running build
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-i5f3magc/LinkChecker/setup.py", line 976, in <module>
      setup(**args)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/tmp/pip-install-i5f3magc/LinkChecker/setup.py", line 476, in run_commands
      super(MyDistribution, self).run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-i5f3magc/LinkChecker/setup.py", line 602, in run
      self.build_message_files()
    File "/tmp/pip-install-i5f3magc/LinkChecker/setup.py", line 592, in build_message_files
      import msgfmt
    File "po/msgfmt.py", line 82
      0x950412deL,       # Magic
                ^
  SyntaxError: invalid syntax
  
  ----------------------------------------
  Failed building wheel for LinkChecker
  Running setup.py clean for LinkChecker
Failed to build LinkChecker
tensorflow-tensorboard 0.4.0rc3 has requirement html5lib==0.9999999, but you'll have html5lib 1.0.1 which is incompatible.
bleach 1.5.0 has requirement html5lib!=0.9999,!=0.99999,<0.99999999,>=0.999, but you'll have html5lib 1.0.1 which is incompatible.
Installing collected packages: LinkChecker
  Running setup.py install for LinkChecker ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-i5f3magc/LinkChecker/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-p93bkc7d/install-record.txt --single-version-externally-managed --compile:
    creating /tmp/pip-install-i5f3magc/LinkChecker/_LinkChecker_configdata.py
    running install
    running build
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-i5f3magc/LinkChecker/setup.py", line 976, in <module>
        setup(**args)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/tmp/pip-install-i5f3magc/LinkChecker/setup.py", line 476, in run_commands
        super(MyDistribution, self).run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-i5f3magc/LinkChecker/setup.py", line 602, in run
        self.build_message_files()
      File "/tmp/pip-install-i5f3magc/LinkChecker/setup.py", line 592, in build_message_files
        import msgfmt
      File "po/msgfmt.py", line 82
        0x950412deL,       # Magic
                  ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-i5f3magc/LinkChecker/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-p93bkc7d/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-i5f3magc/LinkChecker/
```

**Comment by dpalic** [comment]
Thank you for the issue report. Sadly this project is dead, and a new team is around with https://github.com/linkcheck/linkchecker
for more details please see: #708
Also please close this issue and report it freshly on the new repo https://github.com/linkcheck/linkchecker/issues

**Comment by Compro-Prasad** [comment]
Thanks. Someone already reported it before. And thankfully it got resolved there.
