### ISSUE TITLE
ImportError: cannot import name md5

### ISSUE THREAD

**Issue by ishandutta2007** [wummel/linkchecker#775]
I am Trying to install from source on mac

`$ pip install -r requirements.txt --use-mirrors`
> ERROR:root:code for hash md5 was not found.
> Traceback (most recent call last):
>   File "/Users/ishandutta2007/.pyenv/versions/2.7.8/lib/python2.7/hashlib.py", line 139, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/Users/ishandutta2007/.pyenv/versions/2.7.8/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type md5
> ERROR:root:code for hash sha1 was not found.
> Traceback (most recent call last):
>   File "/Users/ishandutta2007/.pyenv/versions/2.7.8/lib/python2.7/hashlib.py", line 139, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/Users/ishandutta2007/.pyenv/versions/2.7.8/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha1
> ERROR:root:code for hash sha224 was not found.
> Traceback (most recent call last):
>   File "/Users/ishandutta2007/.pyenv/versions/2.7.8/lib/python2.7/hashlib.py", line 139, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/Users/ishandutta2007/.pyenv/versions/2.7.8/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha224
> ERROR:root:code for hash sha256 was not found.
> Traceback (most recent call last):
>   File "/Users/ishandutta2007/.pyenv/versions/2.7.8/lib/python2.7/hashlib.py", line 139, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/Users/ishandutta2007/.pyenv/versions/2.7.8/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha256
> ERROR:root:code for hash sha384 was not found.
> Traceback (most recent call last):
>   File "/Users/ishandutta2007/.pyenv/versions/2.7.8/lib/python2.7/hashlib.py", line 139, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/Users/ishandutta2007/.pyenv/versions/2.7.8/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha384
> ERROR:root:code for hash sha512 was not found.
> Traceback (most recent call last):
>   File "/Users/ishandutta2007/.pyenv/versions/2.7.8/lib/python2.7/hashlib.py", line 139, in <module>
>     globals()[__func_name] = __get_hash(__func_name)
>   File "/Users/ishandutta2007/.pyenv/versions/2.7.8/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
>     raise ValueError('unsupported hash type ' + name)
> ValueError: unsupported hash type sha512
> Traceback (most recent call last):
>   File "/Users/ishandutta2007/.pyenv/versions/2.7.8/bin/pip", line 6, in <module>
>     from pip._internal import main
>   File "/Users/ishandutta2007/.pyenv/versions/2.7.8/lib/python2.7/site-packages/pip/_internal/__init__.py", line 19, in <module>
>     from pip._vendor.urllib3.exceptions import DependencyWarning
>   File "/Users/ishandutta2007/.pyenv/versions/2.7.8/lib/python2.7/site-packages/pip/_vendor/urllib3/__init__.py", line 8, in <module>
>     from .connectionpool import (
>   File "/Users/ishandutta2007/.pyenv/versions/2.7.8/lib/python2.7/site-packages/pip/_vendor/urllib3/connectionpool.py", line 29, in <module>
>     from .connection import (
>   File "/Users/ishandutta2007/.pyenv/versions/2.7.8/lib/python2.7/site-packages/pip/_vendor/urllib3/connection.py", line 38, in <module>
>     from .util.ssl_ import (
>   File "/Users/ishandutta2007/.pyenv/versions/2.7.8/lib/python2.7/site-packages/pip/_vendor/urllib3/util/__init__.py", line 6, in <module>
>     from .ssl_ import (
>   File "/Users/ishandutta2007/.pyenv/versions/2.7.8/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py", line 8, in <module>
>     from hashlib import md5, sha1, sha256
> ImportError: cannot import name md5
>

**Comment by matkoniecz** [comment]
note that this project is dead, it was revived at https://github.com/linkchecker/linkchecker which may have fixed this issue already
