### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by MMitchelmore** [wummel/linkchecker#807]
I/you found an internal error in LinkChecker while trying to test the site c:\Users\Mike\documents\Web site\Web files v35\ on my desktop, although why you would want to know this I can't image. Here is the Traceback (most recent call last):
  File "linkcheck\gui\__init__.pyo", line 452, in on_controlButton_clicked
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\gui\__init__.py
    -- code not available --
  File "linkcheck\gui\__init__.pyo", line 438, in start
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\gui\__init__.py
    -- code not available --
  File "linkcheck\gui\__init__.pyo", line 473, in check
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\gui\__init__.py
    -- code not available --
  File "linkcheck\gui\__init__.pyo", line 282, in set_config
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\gui\__init__.py
    -- code not available --
UnboundLocalError: local variable 'pat' referenced before assignment
System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
Requests: 2.2.1
Qt: 4.8.6 / PyQt: 4.11
Modules: QScintilla, Sqlite
Local time: 2021-08-01 15:19:39+011
sys.argv: ['C:\\Program Files (x86)\\LinkChecker\\linkchecker-gui.exe']
Default locale: ('en', 'cp1252')

PS Why is it so complicated to forward this error report to you? I had no interest in signing up to Github apart from being so kind as to send you this error report. I will now uninstall and re-install LinkChecker (which is a great program, by the way) and hope you manage to find the bug before it nips at the next user.

**Comment by matkoniecz** [comment]
note that this project is dead, it was revived at https://github.com/linkchecker/linkchecker which may have fixed this issue

> Why is it so complicated to forward this error report to you? I had no interest in signing up to Github apart from

Github (or other issue tracker requiring registration) is a standard way to report bugs. Some projects use mailing lists or forums (that also require registration)
